const Routes = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  DRAWER_MENU: 'DRAWER_MENU',
  PRODUCT_DETAIL_SCREEN: 'PRODUCT_DETAIL_SCREEN',
  FAVORITE_SCREEN: 'FAVORITE_SCREEN',
  USER_PROFILE_SCREEN: 'USER_PROFILE_SCREEN',
  EDIT_USER_PROFILE_SCREEN: 'EDIT_USER_PROFILE_SCREEN',
  START_UP_SCREEN: 'START_UP_SCREEN',
};

export default Routes;
