const Routes = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  DRAWER_MENU: 'DRAWER_MENU',
  PRODUCT_DETAIL_SCREEN: 'PRODUCT_DETAIL_SCREEN',
  FAVORITE_SCREEN: 'FAVORITE_SCREEN',
};

export default Routes;
